const fs = require('fs');
const path = `./.env`;
const vars = `
    REACT_APP_APPLICATION_KEY=${process.env.REACT_APP_APPLICATION_KEY_NETLIFY}\n
    REACT_APP_CLIENT_ID=${process.env.REACT_APP_CLIENT_ID_NETLIFY}\n
    REACT_APP_SECRET_KEY=${process.env.REACT_APP_SECRET_KEY_NETLIFY}\n
    REACT_APP_X_API_KEY=${process.env.REACT_APP_X_API_KEY_NETLIFY}\n
    REACT_APP_RAWG_API_KEY=${process.env.REACT_APP_RAWG_API_KEY_NETLIFY}\n
    REACT_APP_URL=${process.env.REACT_APP_URL_NETLIFY}\n
    REACT_APP_FIREBASE_API_KEY=${process.env.REACT_APP_FIREBASE_API_KEY_NETLIFY}\n
    REACT_APP_AUTH_DOMAIN=${process.env.REACT_APP_AUTH_DOMAIN_NETLIFY}\n
    REACT_APP_PROJECT_ID=${process.env.REACT_APP_PROJECT_ID_NETLIFY}\n
    REACT_APP_STORAGE_BUCKET=${process.env.REACT_APP_STORAGE_BUCKET_NETLIFY}\n
    REACT_APP_MESSAGING_SENDER_ID=${process.env.REACT_APP_MESSAGING_SENDER_ID_NETLIFY}\n
    REACT_APP_APP_ID=${process.env.REACT_APP_APP_ID_NETLIFY}\n
    REACT_APP_MEASUREMENT_ID=${process.env.REACT_APP_MEASUREMENT_ID_NETLIFY}
`;

fs.writeFileSync(path, vars);