const fs = require('fs')
fs.writeFileSync('./.env', 
`
REACT_APP_API_KEY=${process.env.API_KEY}\n
REACT_APP_APPLICATION_KEY=${process.env.REACT_APP_APPLICATION_KEY}\n
REACT_APP_CLIENT_ID=${process.env.REACT_APP_CLIENT_ID}\n
REACT_APP_SECRET_KEY=${process.env.REACT_APP_SECRET_KEY}\n
REACT_APP_X_API_KEY=${process.env.REACT_APP_X_API_KEY}\n
REACT_APP_RAWG_API_KEY=${process.env.REACT_APP_RAWG_API_KEY}\n
REACT_APP_URL=${process.env.REACT_APP_URL}\n
REACT_APP_FIREBASE_API_KEY=${process.env.REACT_APP_FIREBASE_API_KEY}\n
REACT_APP_AUTH_DOMAIN=${process.env.REACT_APP_AUTH_DOMAIN}\n
REACT_APP_PROJECT_ID=${process.env.REACT_APP_PROJECT_ID}\n
REACT_APP_STORAGE_BUCKET=${process.env.REACT_APP_STORAGE_BUCKET}\n
REACT_APP_MESSAGING_SENDER_ID=${process.env.REACT_APP_MESSAGING_SENDER_ID}\n
REACT_APP_APP_ID=${process.env.REACT_APP_APP_ID}\n
REACT_APP_MEASUREMENT_ID=${process.env.REACT_APP_MEASUREMENT_ID}\n
`)